package org.zdb.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ElectricAutoExample {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table electric_auto
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table electric_auto
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table electric_auto
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table electric_auto
     *
     * @mbggenerated
     */
    protected Integer limitStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table electric_auto
     *
     * @mbggenerated
     */
    protected Integer limitEnd;

    /**
     *  构造查询条件,electric_auto
     */
    public ElectricAutoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     *  设置排序字段,electric_auto
     *
     * @param orderByClause 排序字段
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     *  获取排序字段,electric_auto
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     *  设置过滤重复数据,electric_auto
     *
     * @param distinct 是否过滤重复数据
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     *  是否过滤重复数据,electric_auto
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     *  获取当前的查询条件实例,electric_auto
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * ,electric_auto
     *
     * @param criteria 过滤条件实例
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * ,electric_auto
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     *  创建一个查询条件,electric_auto
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     *  内部构建查询条件对象,electric_auto
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     *  清除查询条件,electric_auto
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * ,electric_auto
     *
     * @param limitStart
     */
    public void setLimitStart(Integer limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * ,electric_auto
     */
    public Integer getLimitStart() {
        return limitStart;
    }

    /**
     * ,electric_auto
     *
     * @param limitEnd
     */
    public void setLimitEnd(Integer limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * ,electric_auto
     */
    public Integer getLimitEnd() {
        return limitEnd;
    }

    /**
     * 4.4.5电表-自动抄表记录
     * GeneratedCriteria
     * 数据库表：electric_auto
     */
    protected abstract static class GeneratedCriteria {

        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andEaIdIsNull() {
            addCriterion("ea_id is null");
            return (Criteria) this;
        }

        public Criteria andEaIdIsNotNull() {
            addCriterion("ea_id is not null");
            return (Criteria) this;
        }

        public Criteria andEaIdEqualTo(Long value) {
            addCriterion("ea_id =", value, "eaId");
            return (Criteria) this;
        }

        public Criteria andEaIdNotEqualTo(Long value) {
            addCriterion("ea_id <>", value, "eaId");
            return (Criteria) this;
        }

        public Criteria andEaIdGreaterThan(Long value) {
            addCriterion("ea_id >", value, "eaId");
            return (Criteria) this;
        }

        public Criteria andEaIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ea_id >=", value, "eaId");
            return (Criteria) this;
        }

        public Criteria andEaIdLessThan(Long value) {
            addCriterion("ea_id <", value, "eaId");
            return (Criteria) this;
        }

        public Criteria andEaIdLessThanOrEqualTo(Long value) {
            addCriterion("ea_id <=", value, "eaId");
            return (Criteria) this;
        }

        public Criteria andEaIdIn(List<Long> values) {
            addCriterion("ea_id in", values, "eaId");
            return (Criteria) this;
        }

        public Criteria andEaIdNotIn(List<Long> values) {
            addCriterion("ea_id not in", values, "eaId");
            return (Criteria) this;
        }

        public Criteria andEaIdBetween(Long value1, Long value2) {
            addCriterion("ea_id between", value1, value2, "eaId");
            return (Criteria) this;
        }

        public Criteria andEaIdNotBetween(Long value1, Long value2) {
            addCriterion("ea_id not between", value1, value2, "eaId");
            return (Criteria) this;
        }

        public Criteria andEaEqIdIsNull() {
            addCriterion("ea_eq_id is null");
            return (Criteria) this;
        }

        public Criteria andEaEqIdIsNotNull() {
            addCriterion("ea_eq_id is not null");
            return (Criteria) this;
        }

        public Criteria andEaEqIdEqualTo(Long value) {
            addCriterion("ea_eq_id =", value, "eaEqId");
            return (Criteria) this;
        }

        public Criteria andEaEqIdNotEqualTo(Long value) {
            addCriterion("ea_eq_id <>", value, "eaEqId");
            return (Criteria) this;
        }

        public Criteria andEaEqIdGreaterThan(Long value) {
            addCriterion("ea_eq_id >", value, "eaEqId");
            return (Criteria) this;
        }

        public Criteria andEaEqIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ea_eq_id >=", value, "eaEqId");
            return (Criteria) this;
        }

        public Criteria andEaEqIdLessThan(Long value) {
            addCriterion("ea_eq_id <", value, "eaEqId");
            return (Criteria) this;
        }

        public Criteria andEaEqIdLessThanOrEqualTo(Long value) {
            addCriterion("ea_eq_id <=", value, "eaEqId");
            return (Criteria) this;
        }

        public Criteria andEaEqIdIn(List<Long> values) {
            addCriterion("ea_eq_id in", values, "eaEqId");
            return (Criteria) this;
        }

        public Criteria andEaEqIdNotIn(List<Long> values) {
            addCriterion("ea_eq_id not in", values, "eaEqId");
            return (Criteria) this;
        }

        public Criteria andEaEqIdBetween(Long value1, Long value2) {
            addCriterion("ea_eq_id between", value1, value2, "eaEqId");
            return (Criteria) this;
        }

        public Criteria andEaEqIdNotBetween(Long value1, Long value2) {
            addCriterion("ea_eq_id not between", value1, value2, "eaEqId");
            return (Criteria) this;
        }

        public Criteria andEaChannelIdIsNull() {
            addCriterion("ea_channel_id is null");
            return (Criteria) this;
        }

        public Criteria andEaChannelIdIsNotNull() {
            addCriterion("ea_channel_id is not null");
            return (Criteria) this;
        }

        public Criteria andEaChannelIdEqualTo(Long value) {
            addCriterion("ea_channel_id =", value, "eaChannelId");
            return (Criteria) this;
        }

        public Criteria andEaChannelIdNotEqualTo(Long value) {
            addCriterion("ea_channel_id <>", value, "eaChannelId");
            return (Criteria) this;
        }

        public Criteria andEaChannelIdGreaterThan(Long value) {
            addCriterion("ea_channel_id >", value, "eaChannelId");
            return (Criteria) this;
        }

        public Criteria andEaChannelIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ea_channel_id >=", value, "eaChannelId");
            return (Criteria) this;
        }

        public Criteria andEaChannelIdLessThan(Long value) {
            addCriterion("ea_channel_id <", value, "eaChannelId");
            return (Criteria) this;
        }

        public Criteria andEaChannelIdLessThanOrEqualTo(Long value) {
            addCriterion("ea_channel_id <=", value, "eaChannelId");
            return (Criteria) this;
        }

        public Criteria andEaChannelIdIn(List<Long> values) {
            addCriterion("ea_channel_id in", values, "eaChannelId");
            return (Criteria) this;
        }

        public Criteria andEaChannelIdNotIn(List<Long> values) {
            addCriterion("ea_channel_id not in", values, "eaChannelId");
            return (Criteria) this;
        }

        public Criteria andEaChannelIdBetween(Long value1, Long value2) {
            addCriterion("ea_channel_id between", value1, value2, "eaChannelId");
            return (Criteria) this;
        }

        public Criteria andEaChannelIdNotBetween(Long value1, Long value2) {
            addCriterion("ea_channel_id not between", value1, value2, "eaChannelId");
            return (Criteria) this;
        }

        public Criteria andEaTimeIsNull() {
            addCriterion("ea_time is null");
            return (Criteria) this;
        }

        public Criteria andEaTimeIsNotNull() {
            addCriterion("ea_time is not null");
            return (Criteria) this;
        }

        public Criteria andEaTimeEqualTo(Date value) {
            addCriterion("ea_time =", value, "eaTime");
            return (Criteria) this;
        }

        public Criteria andEaTimeNotEqualTo(Date value) {
            addCriterion("ea_time <>", value, "eaTime");
            return (Criteria) this;
        }

        public Criteria andEaTimeGreaterThan(Date value) {
            addCriterion("ea_time >", value, "eaTime");
            return (Criteria) this;
        }

        public Criteria andEaTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ea_time >=", value, "eaTime");
            return (Criteria) this;
        }

        public Criteria andEaTimeLessThan(Date value) {
            addCriterion("ea_time <", value, "eaTime");
            return (Criteria) this;
        }

        public Criteria andEaTimeLessThanOrEqualTo(Date value) {
            addCriterion("ea_time <=", value, "eaTime");
            return (Criteria) this;
        }

        public Criteria andEaTimeIn(List<Date> values) {
            addCriterion("ea_time in", values, "eaTime");
            return (Criteria) this;
        }

        public Criteria andEaTimeNotIn(List<Date> values) {
            addCriterion("ea_time not in", values, "eaTime");
            return (Criteria) this;
        }

        public Criteria andEaTimeBetween(Date value1, Date value2) {
            addCriterion("ea_time between", value1, value2, "eaTime");
            return (Criteria) this;
        }

        public Criteria andEaTimeNotBetween(Date value1, Date value2) {
            addCriterion("ea_time not between", value1, value2, "eaTime");
            return (Criteria) this;
        }

        public Criteria andEaReadNumIsNull() {
            addCriterion("ea_read_num is null");
            return (Criteria) this;
        }

        public Criteria andEaReadNumIsNotNull() {
            addCriterion("ea_read_num is not null");
            return (Criteria) this;
        }

        public Criteria andEaReadNumEqualTo(BigDecimal value) {
            addCriterion("ea_read_num =", value, "eaReadNum");
            return (Criteria) this;
        }

        public Criteria andEaReadNumNotEqualTo(BigDecimal value) {
            addCriterion("ea_read_num <>", value, "eaReadNum");
            return (Criteria) this;
        }

        public Criteria andEaReadNumGreaterThan(BigDecimal value) {
            addCriterion("ea_read_num >", value, "eaReadNum");
            return (Criteria) this;
        }

        public Criteria andEaReadNumGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ea_read_num >=", value, "eaReadNum");
            return (Criteria) this;
        }

        public Criteria andEaReadNumLessThan(BigDecimal value) {
            addCriterion("ea_read_num <", value, "eaReadNum");
            return (Criteria) this;
        }

        public Criteria andEaReadNumLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ea_read_num <=", value, "eaReadNum");
            return (Criteria) this;
        }

        public Criteria andEaReadNumIn(List<BigDecimal> values) {
            addCriterion("ea_read_num in", values, "eaReadNum");
            return (Criteria) this;
        }

        public Criteria andEaReadNumNotIn(List<BigDecimal> values) {
            addCriterion("ea_read_num not in", values, "eaReadNum");
            return (Criteria) this;
        }

        public Criteria andEaReadNumBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ea_read_num between", value1, value2, "eaReadNum");
            return (Criteria) this;
        }

        public Criteria andEaReadNumNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ea_read_num not between", value1, value2, "eaReadNum");
            return (Criteria) this;
        }

        public Criteria andEaResidueNumIsNull() {
            addCriterion("ea_residue_num is null");
            return (Criteria) this;
        }

        public Criteria andEaResidueNumIsNotNull() {
            addCriterion("ea_residue_num is not null");
            return (Criteria) this;
        }

        public Criteria andEaResidueNumEqualTo(BigDecimal value) {
            addCriterion("ea_residue_num =", value, "eaResidueNum");
            return (Criteria) this;
        }

        public Criteria andEaResidueNumNotEqualTo(BigDecimal value) {
            addCriterion("ea_residue_num <>", value, "eaResidueNum");
            return (Criteria) this;
        }

        public Criteria andEaResidueNumGreaterThan(BigDecimal value) {
            addCriterion("ea_residue_num >", value, "eaResidueNum");
            return (Criteria) this;
        }

        public Criteria andEaResidueNumGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ea_residue_num >=", value, "eaResidueNum");
            return (Criteria) this;
        }

        public Criteria andEaResidueNumLessThan(BigDecimal value) {
            addCriterion("ea_residue_num <", value, "eaResidueNum");
            return (Criteria) this;
        }

        public Criteria andEaResidueNumLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ea_residue_num <=", value, "eaResidueNum");
            return (Criteria) this;
        }

        public Criteria andEaResidueNumIn(List<BigDecimal> values) {
            addCriterion("ea_residue_num in", values, "eaResidueNum");
            return (Criteria) this;
        }

        public Criteria andEaResidueNumNotIn(List<BigDecimal> values) {
            addCriterion("ea_residue_num not in", values, "eaResidueNum");
            return (Criteria) this;
        }

        public Criteria andEaResidueNumBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ea_residue_num between", value1, value2, "eaResidueNum");
            return (Criteria) this;
        }

        public Criteria andEaResidueNumNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ea_residue_num not between", value1, value2, "eaResidueNum");
            return (Criteria) this;
        }

        public Criteria andEaUseNumIsNull() {
            addCriterion("ea_use_num is null");
            return (Criteria) this;
        }

        public Criteria andEaUseNumIsNotNull() {
            addCriterion("ea_use_num is not null");
            return (Criteria) this;
        }

        public Criteria andEaUseNumEqualTo(BigDecimal value) {
            addCriterion("ea_use_num =", value, "eaUseNum");
            return (Criteria) this;
        }

        public Criteria andEaUseNumNotEqualTo(BigDecimal value) {
            addCriterion("ea_use_num <>", value, "eaUseNum");
            return (Criteria) this;
        }

        public Criteria andEaUseNumGreaterThan(BigDecimal value) {
            addCriterion("ea_use_num >", value, "eaUseNum");
            return (Criteria) this;
        }

        public Criteria andEaUseNumGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ea_use_num >=", value, "eaUseNum");
            return (Criteria) this;
        }

        public Criteria andEaUseNumLessThan(BigDecimal value) {
            addCriterion("ea_use_num <", value, "eaUseNum");
            return (Criteria) this;
        }

        public Criteria andEaUseNumLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ea_use_num <=", value, "eaUseNum");
            return (Criteria) this;
        }

        public Criteria andEaUseNumIn(List<BigDecimal> values) {
            addCriterion("ea_use_num in", values, "eaUseNum");
            return (Criteria) this;
        }

        public Criteria andEaUseNumNotIn(List<BigDecimal> values) {
            addCriterion("ea_use_num not in", values, "eaUseNum");
            return (Criteria) this;
        }

        public Criteria andEaUseNumBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ea_use_num between", value1, value2, "eaUseNum");
            return (Criteria) this;
        }

        public Criteria andEaUseNumNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ea_use_num not between", value1, value2, "eaUseNum");
            return (Criteria) this;
        }

        public Criteria andEaSharpNumIsNull() {
            addCriterion("ea_sharp_num is null");
            return (Criteria) this;
        }

        public Criteria andEaSharpNumIsNotNull() {
            addCriterion("ea_sharp_num is not null");
            return (Criteria) this;
        }

        public Criteria andEaSharpNumEqualTo(BigDecimal value) {
            addCriterion("ea_sharp_num =", value, "eaSharpNum");
            return (Criteria) this;
        }

        public Criteria andEaSharpNumNotEqualTo(BigDecimal value) {
            addCriterion("ea_sharp_num <>", value, "eaSharpNum");
            return (Criteria) this;
        }

        public Criteria andEaSharpNumGreaterThan(BigDecimal value) {
            addCriterion("ea_sharp_num >", value, "eaSharpNum");
            return (Criteria) this;
        }

        public Criteria andEaSharpNumGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ea_sharp_num >=", value, "eaSharpNum");
            return (Criteria) this;
        }

        public Criteria andEaSharpNumLessThan(BigDecimal value) {
            addCriterion("ea_sharp_num <", value, "eaSharpNum");
            return (Criteria) this;
        }

        public Criteria andEaSharpNumLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ea_sharp_num <=", value, "eaSharpNum");
            return (Criteria) this;
        }

        public Criteria andEaSharpNumIn(List<BigDecimal> values) {
            addCriterion("ea_sharp_num in", values, "eaSharpNum");
            return (Criteria) this;
        }

        public Criteria andEaSharpNumNotIn(List<BigDecimal> values) {
            addCriterion("ea_sharp_num not in", values, "eaSharpNum");
            return (Criteria) this;
        }

        public Criteria andEaSharpNumBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ea_sharp_num between", value1, value2, "eaSharpNum");
            return (Criteria) this;
        }

        public Criteria andEaSharpNumNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ea_sharp_num not between", value1, value2, "eaSharpNum");
            return (Criteria) this;
        }

        public Criteria andEaPeakNumIsNull() {
            addCriterion("ea_peak_num is null");
            return (Criteria) this;
        }

        public Criteria andEaPeakNumIsNotNull() {
            addCriterion("ea_peak_num is not null");
            return (Criteria) this;
        }

        public Criteria andEaPeakNumEqualTo(BigDecimal value) {
            addCriterion("ea_peak_num =", value, "eaPeakNum");
            return (Criteria) this;
        }

        public Criteria andEaPeakNumNotEqualTo(BigDecimal value) {
            addCriterion("ea_peak_num <>", value, "eaPeakNum");
            return (Criteria) this;
        }

        public Criteria andEaPeakNumGreaterThan(BigDecimal value) {
            addCriterion("ea_peak_num >", value, "eaPeakNum");
            return (Criteria) this;
        }

        public Criteria andEaPeakNumGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ea_peak_num >=", value, "eaPeakNum");
            return (Criteria) this;
        }

        public Criteria andEaPeakNumLessThan(BigDecimal value) {
            addCriterion("ea_peak_num <", value, "eaPeakNum");
            return (Criteria) this;
        }

        public Criteria andEaPeakNumLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ea_peak_num <=", value, "eaPeakNum");
            return (Criteria) this;
        }

        public Criteria andEaPeakNumIn(List<BigDecimal> values) {
            addCriterion("ea_peak_num in", values, "eaPeakNum");
            return (Criteria) this;
        }

        public Criteria andEaPeakNumNotIn(List<BigDecimal> values) {
            addCriterion("ea_peak_num not in", values, "eaPeakNum");
            return (Criteria) this;
        }

        public Criteria andEaPeakNumBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ea_peak_num between", value1, value2, "eaPeakNum");
            return (Criteria) this;
        }

        public Criteria andEaPeakNumNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ea_peak_num not between", value1, value2, "eaPeakNum");
            return (Criteria) this;
        }

        public Criteria andEaFlatNumIsNull() {
            addCriterion("ea_flat_num is null");
            return (Criteria) this;
        }

        public Criteria andEaFlatNumIsNotNull() {
            addCriterion("ea_flat_num is not null");
            return (Criteria) this;
        }

        public Criteria andEaFlatNumEqualTo(BigDecimal value) {
            addCriterion("ea_flat_num =", value, "eaFlatNum");
            return (Criteria) this;
        }

        public Criteria andEaFlatNumNotEqualTo(BigDecimal value) {
            addCriterion("ea_flat_num <>", value, "eaFlatNum");
            return (Criteria) this;
        }

        public Criteria andEaFlatNumGreaterThan(BigDecimal value) {
            addCriterion("ea_flat_num >", value, "eaFlatNum");
            return (Criteria) this;
        }

        public Criteria andEaFlatNumGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ea_flat_num >=", value, "eaFlatNum");
            return (Criteria) this;
        }

        public Criteria andEaFlatNumLessThan(BigDecimal value) {
            addCriterion("ea_flat_num <", value, "eaFlatNum");
            return (Criteria) this;
        }

        public Criteria andEaFlatNumLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ea_flat_num <=", value, "eaFlatNum");
            return (Criteria) this;
        }

        public Criteria andEaFlatNumIn(List<BigDecimal> values) {
            addCriterion("ea_flat_num in", values, "eaFlatNum");
            return (Criteria) this;
        }

        public Criteria andEaFlatNumNotIn(List<BigDecimal> values) {
            addCriterion("ea_flat_num not in", values, "eaFlatNum");
            return (Criteria) this;
        }

        public Criteria andEaFlatNumBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ea_flat_num between", value1, value2, "eaFlatNum");
            return (Criteria) this;
        }

        public Criteria andEaFlatNumNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ea_flat_num not between", value1, value2, "eaFlatNum");
            return (Criteria) this;
        }

        public Criteria andEaValleyNumIsNull() {
            addCriterion("ea_valley_num is null");
            return (Criteria) this;
        }

        public Criteria andEaValleyNumIsNotNull() {
            addCriterion("ea_valley_num is not null");
            return (Criteria) this;
        }

        public Criteria andEaValleyNumEqualTo(BigDecimal value) {
            addCriterion("ea_valley_num =", value, "eaValleyNum");
            return (Criteria) this;
        }

        public Criteria andEaValleyNumNotEqualTo(BigDecimal value) {
            addCriterion("ea_valley_num <>", value, "eaValleyNum");
            return (Criteria) this;
        }

        public Criteria andEaValleyNumGreaterThan(BigDecimal value) {
            addCriterion("ea_valley_num >", value, "eaValleyNum");
            return (Criteria) this;
        }

        public Criteria andEaValleyNumGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ea_valley_num >=", value, "eaValleyNum");
            return (Criteria) this;
        }

        public Criteria andEaValleyNumLessThan(BigDecimal value) {
            addCriterion("ea_valley_num <", value, "eaValleyNum");
            return (Criteria) this;
        }

        public Criteria andEaValleyNumLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ea_valley_num <=", value, "eaValleyNum");
            return (Criteria) this;
        }

        public Criteria andEaValleyNumIn(List<BigDecimal> values) {
            addCriterion("ea_valley_num in", values, "eaValleyNum");
            return (Criteria) this;
        }

        public Criteria andEaValleyNumNotIn(List<BigDecimal> values) {
            addCriterion("ea_valley_num not in", values, "eaValleyNum");
            return (Criteria) this;
        }

        public Criteria andEaValleyNumBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ea_valley_num between", value1, value2, "eaValleyNum");
            return (Criteria) this;
        }

        public Criteria andEaValleyNumNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ea_valley_num not between", value1, value2, "eaValleyNum");
            return (Criteria) this;
        }

        public Criteria andEaCreateAdminIsNull() {
            addCriterion("ea_create_admin is null");
            return (Criteria) this;
        }

        public Criteria andEaCreateAdminIsNotNull() {
            addCriterion("ea_create_admin is not null");
            return (Criteria) this;
        }

        public Criteria andEaCreateAdminEqualTo(String value) {
            addCriterion("ea_create_admin =", value, "eaCreateAdmin");
            return (Criteria) this;
        }

        public Criteria andEaCreateAdminNotEqualTo(String value) {
            addCriterion("ea_create_admin <>", value, "eaCreateAdmin");
            return (Criteria) this;
        }

        public Criteria andEaCreateAdminGreaterThan(String value) {
            addCriterion("ea_create_admin >", value, "eaCreateAdmin");
            return (Criteria) this;
        }

        public Criteria andEaCreateAdminGreaterThanOrEqualTo(String value) {
            addCriterion("ea_create_admin >=", value, "eaCreateAdmin");
            return (Criteria) this;
        }

        public Criteria andEaCreateAdminLessThan(String value) {
            addCriterion("ea_create_admin <", value, "eaCreateAdmin");
            return (Criteria) this;
        }

        public Criteria andEaCreateAdminLessThanOrEqualTo(String value) {
            addCriterion("ea_create_admin <=", value, "eaCreateAdmin");
            return (Criteria) this;
        }

        public Criteria andEaCreateAdminLike(String value) {
            addCriterion("ea_create_admin like", value, "eaCreateAdmin");
            return (Criteria) this;
        }

        public Criteria andEaCreateAdminNotLike(String value) {
            addCriterion("ea_create_admin not like", value, "eaCreateAdmin");
            return (Criteria) this;
        }

        public Criteria andEaCreateAdminIn(List<String> values) {
            addCriterion("ea_create_admin in", values, "eaCreateAdmin");
            return (Criteria) this;
        }

        public Criteria andEaCreateAdminNotIn(List<String> values) {
            addCriterion("ea_create_admin not in", values, "eaCreateAdmin");
            return (Criteria) this;
        }

        public Criteria andEaCreateAdminBetween(String value1, String value2) {
            addCriterion("ea_create_admin between", value1, value2, "eaCreateAdmin");
            return (Criteria) this;
        }

        public Criteria andEaCreateAdminNotBetween(String value1, String value2) {
            addCriterion("ea_create_admin not between", value1, value2, "eaCreateAdmin");
            return (Criteria) this;
        }

        public Criteria andEaNeedIsNull() {
            addCriterion("ea_need is null");
            return (Criteria) this;
        }

        public Criteria andEaNeedIsNotNull() {
            addCriterion("ea_need is not null");
            return (Criteria) this;
        }

        public Criteria andEaNeedEqualTo(Long value) {
            addCriterion("ea_need =", value, "eaNeed");
            return (Criteria) this;
        }

        public Criteria andEaNeedNotEqualTo(Long value) {
            addCriterion("ea_need <>", value, "eaNeed");
            return (Criteria) this;
        }

        public Criteria andEaNeedGreaterThan(Long value) {
            addCriterion("ea_need >", value, "eaNeed");
            return (Criteria) this;
        }

        public Criteria andEaNeedGreaterThanOrEqualTo(Long value) {
            addCriterion("ea_need >=", value, "eaNeed");
            return (Criteria) this;
        }

        public Criteria andEaNeedLessThan(Long value) {
            addCriterion("ea_need <", value, "eaNeed");
            return (Criteria) this;
        }

        public Criteria andEaNeedLessThanOrEqualTo(Long value) {
            addCriterion("ea_need <=", value, "eaNeed");
            return (Criteria) this;
        }

        public Criteria andEaNeedIn(List<Long> values) {
            addCriterion("ea_need in", values, "eaNeed");
            return (Criteria) this;
        }

        public Criteria andEaNeedNotIn(List<Long> values) {
            addCriterion("ea_need not in", values, "eaNeed");
            return (Criteria) this;
        }

        public Criteria andEaNeedBetween(Long value1, Long value2) {
            addCriterion("ea_need between", value1, value2, "eaNeed");
            return (Criteria) this;
        }

        public Criteria andEaNeedNotBetween(Long value1, Long value2) {
            addCriterion("ea_need not between", value1, value2, "eaNeed");
            return (Criteria) this;
        }
    }

    /**
     * 类注释
     * Criteria
     * 数据库表：electric_auto
     */
    public static class Criteria extends GeneratedCriteria {


        protected Criteria() {
            super();
        }
    }

    /**
     * 4.4.5电表-自动抄表记录
     * Criterion
     * 数据库表：electric_auto
     */
    public static class Criterion {

        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}